FROM golang:1.24-alpine AS builder

WORKDIR /build

# Копируем файлы go.mod и go.sum отдельно, чтобы кешировать зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем оставшиеся файлы проекта
COPY . .

# Собираем бинарник
RUN go build -o ./userapi ./cmd/server/main.go

# Минимальный образ без лишнего мусора
FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /build/userapi ./userapi

CMD ["/app/userapi"]
