version: "3.8"

services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_project
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - app_network
  grpc-server:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.server
    container_name: grpc-server
    ports:
      - "9001:9001"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/crud_project?sslmode=disable
    depends_on:
      - db
    networks:
      - app_network

  grpc-client:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.client
    container_name: grpc-client
    depends_on:
      - grpc-server
    networks:
      - app_network



networks:
  app_network:
    driver: bridge